modLoader = "javafml"
loaderVersion = "[${forge},)"
issueTrackerURL = "https://github.com/lopyluna/create-calamity/issues"
license = "MIT"

[[mods]]
modId = "calamity"
version = "${version}"
displayName = "Create Calamity"
authors = "everybody"
description = '''
lol
'''
logoFile = "icon.png"

[[dependencies.calamity]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.calamity]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.calamity]]
modId="create"
mandatory=true
versionRange="[${create_forge},)"
ordering="NONE"
side="BOTH"